AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rust-sample

  Sample SAM Template for rust-sample

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SchemaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
  
  AppEventBus: 
    Type: AWS::Events::EventBus
    Properties: 
        Name: "prod.appeventbus"

  PublishApi:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: publisher
    Properties:
      CodeUri: .
      Handler: bootstrap.is.the.handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        PublishApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /publish
            Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref SchemaTable
          EVENT_BUS_NAME: !Ref AppEventBus
          MOMENTO_AUTH_TOKEN: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZAamFtZXNlYXN0aGFtLmNvLnVrIiwiY3AiOiJjb250cm9sLmNlbGwtdXMtZWFzdC0xLTEucHJvZC5hLm1vbWVudG9ocS5jb20iLCJjIjoiY2FjaGUuY2VsbC11cy1lYXN0LTEtMS5wcm9kLmEubW9tZW50b2hxLmNvbSJ9.B32W_JrBlcYrsrAB6ndm4i8TpfZsg2NmvXmMeM-5hNY4yQ9UxPgoOgUS0-CDkph0_feqjJGPyoWe7z9fnHeTmA"
      Policies:
        - DynamoDBReadPolicy: # More info about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
            TableName: !Ref SchemaTable
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref AppEventBus

  RegisterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: register
    Properties:
      CodeUri: .
      Handler: bootstrap.is.the.handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        RegisterApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /register
            Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref SchemaTable
      Policies:
        - DynamoDBWritePolicy: # More info about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
            TableName: !Ref SchemaTable

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EventProxyApi:
    Description: "API Gateway endpoint URL for Prod stage for Put function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"